# Generated by Django 5.2.1 on 2025-05-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSeriesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_utc', models.DateTimeField()),
                ('hydraulic_71', models.FloatField(blank=True, null=True)),
                ('hydraulic_36', models.FloatField(blank=True, null=True)),
                ('hydraulic_1', models.FloatField(blank=True, null=True)),
                ('solar_14', models.FloatField(blank=True, null=True)),
                ('wind_12', models.FloatField(blank=True, null=True)),
                ('nuclear_39', models.FloatField(blank=True, null=True)),
                ('nuclear_4', models.FloatField(blank=True, null=True)),
                ('nuclear_74', models.FloatField(blank=True, null=True)),
                ('peninsula_forecast_460', models.FloatField(blank=True, null=True)),
                ('scheduled_demand_365', models.FloatField(blank=True, null=True)),
                ('scheduled_demand_358', models.FloatField(blank=True, null=True)),
                ('scheduled_demand_372', models.FloatField(blank=True, null=True)),
                ('daily_spot_market_600_España', models.FloatField(blank=True, null=True)),
                ('daily_spot_market_600_Portugal', models.FloatField(blank=True, null=True)),
                ('average_demand_price_573_Baleares', models.FloatField(blank=True, null=True)),
                ('average_demand_price_573_Canarias', models.FloatField(blank=True, null=True)),
                ('average_demand_price_573_Ceuta', models.FloatField(blank=True, null=True)),
                ('average_demand_price_573_Melilla', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['datetime_utc'],
            },
        ),
    ]
