# Generated by Django 5.2.1 on 2025-06-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_used', models.CharField(max_length=50)),
                ('hours_ahead', models.IntegerField()),
                ('input_hours', models.IntegerField()),
                ('prediction_date', models.DateField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('predictions', models.JSONField()),
                ('timestamps', models.JSONField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='core_predic_created_b9efcc_idx'), models.Index(fields=['model_used'], name='core_predic_model_u_9d90b5_idx'), models.Index(fields=['prediction_date'], name='core_predic_predict_453968_idx')],
            },
        ),
    ]
