FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Here I bind to 0.0.0.0 to allow connections from outside the container (as the host machine or other containers)
CMD ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:7777"] 

EXPOSE 7777
