FROM oven/bun:1 as base

WORKDIR /app

COPY frontend/package*.json frontend/bun.lockb* ./

RUN bun install

COPY frontend/ .

EXPOSE 8888

CMD ["bun", "run", "dev", "--host", "0.0.0.0", "--port", "8888"]
